{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-chart-base.fullname" . }}-web
  labels:
    {{- include "tenant-chart-base.labels" . | nindent 4 }}
    digest-pipeline.io/service: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "digest-pipeline.selectorLabels" (dict "Values" .Values "Release" .Release "Chart" .Chart "service" "web") | nindent 4 }}
{{- end }}
